### ISSUE TITLE
Island minor highways - carreteras conectadas a un área

### ISSUE THREAD

**Issue by karitotp** [osmlab/osmlint#107]
@Rub21  en el trabajo en island minor highways eh estado encontrando errores de este tipo: 

![island](https://cloud.githubusercontent.com/assets/11504548/15222649/5f96365c-1836-11e6-8ceb-0115b13bbda2.png)

EL error se muestra debido a que la carretera  esta conectada a un area con éstos tags:

![tag](https://cloud.githubusercontent.com/assets/11504548/15222670/7811d7d6-1836-11e6-9d3f-b723d26e4d9a.png)

**Comment by Rub21** [comment]
close!
