### ISSUE TITLE
Numero incorrecto de lanes 

### ISSUE THREAD

**Issue by dannykath** [osmlab/osmlint#108]
@Rub21 , habria alguna forma de verificar esto : 
https://www.openstreetmap.org/way/417286236/history

![captura de pantalla de 2016-05-13 17 08 17](https://cloud.githubusercontent.com/assets/8483644/15263202/7b47b266-192d-11e6-8a65-3a70a6361faf.png)
![2](https://cloud.githubusercontent.com/assets/8483644/15263203/81915f3c-192d-11e6-8e94-b79c3c84fe41.png)

Ya que cuando validas, no genera error 

![3](https://cloud.githubusercontent.com/assets/8483644/15263209/8e725602-192d-11e6-8424-f9f5a7055ee0.png)

**Comment by Rub21** [comment]
done! https://github.com/osmlab/osmlint/pull/117
