### ISSUE TITLE
Update validators

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#110]
The new mbtiles release has different  formats for `properties` , We need update validators to support it. 

```js
"@id":209358234,"@type":"way","@version":5,"@changeset":33945329,"@uid":224342,"@user":"mircozorzo","@timestamp":1441925653,
```
cc @geohacker @maning.

**Comment by aaronlidman** [comment]
@Rub21 - What changed with the mbtiles exactly? In the qa-tiles?

**Comment by Rub21** [comment]
@aaronlidman .

For example: 

in the previous version the id of way was `properties._osm_way_id`  and  the currently version is `properties.["@id"]`

same case for other properties. 
```
"@id":209358234,
"@type":"way",
"@version":5,
"@changeset":33945329,
"@uid":224342,
"@user":"mircozorzo",
"@timestamp":1441925653
```

**Comment by Rub21** [comment]
@geohacker  maybe the testing will fail because the mbtiles  are old. we need to update the mbtiles. 

For now I will just focusing  on update the  validators and run on detection for to-fix. when I get free i will update the testing.

**Comment by Rub21** [comment]
done!
