### ISSUE TITLE
Find motorway_link with missing oneway tags

### ISSUE THREAD

**Issue by planemad** [osmlab/osmlint#116]
The recent OSRM update https://github.com/Project-OSRM/osrm-backend/pull/2491 does not automatically consider every motorway_link as oneway anymore.

Motorway links with missing `oneway` tags in OSM may now create incorrect routes. We need a linter to detect such links so that mappers can add the `oneway=yes` if required.

**Sketch**
- Find ways tagged `highway=motorway_link` without `oneway` tag
- If the link is connected to a `highway=motorway` with a `oneway`, it might also be a `oneway`

We can load these into to-fix for later review.

cc @Rub21

**Comment by Rub21** [comment]
@planemad  can you check on the detection http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink
 also the validator https://github.com/osmlab/osmlint/tree/missingoneway/validators/missingOneway.

**Comment by planemad** [comment]
@Rub21 looking fantastic! Most of the incorrect detections are two way links connected to other one way links. These can be dropped.

**False positives - Not an error**
- Links between two motorways https://www.openstreetmap.org/way/248995749 
- Links with `access=no` <br><img width="242" alt="screenshot 2016-06-07 11 52 03" src="https://cloud.githubusercontent.com/assets/126868/15847790/572d78ca-2ca6-11e6-8e80-d7875735b232.png">
- Link connected to another oneway link https://www.openstreetmap.org/way/21288171<br>
<img width="513" alt="screenshot 2016-06-07 11 57 16" src="https://cloud.githubusercontent.com/assets/126868/15847881/02ab92f4-2ca7-11e6-87d7-f4bc0b16ca9d.png"><br>
<img width="288" alt="screenshot 2016-06-07 11 59 59" src="https://cloud.githubusercontent.com/assets/126868/15847936/62b43912-2ca7-11e6-8625-0e3ee33926d8.png"><br>
<img width="379" alt="screenshot 2016-06-07 12 30 03" src="https://cloud.githubusercontent.com/assets/126868/15848738/5a08604a-2cac-11e6-89cc-a7e0e2bfd568.png">

**Comment by Rub21** [comment]
@planemad  I fix the code to avoid false positive, could you check  http://osmlab.github.io/to-fix/#/task/missingonewaysmotorwaylink ?

**Comment by Rub21** [comment]
@planemad ^^

**Comment by planemad** [comment]
@Rub21 sorry, missed this. Results look excellent, error rate is 1 in 10.

False positives:
- https://www.openstreetmap.org/way/421273035

I think the task is ready to hit, if you can fix ^ even better.

cc @maning @andygol

**Comment by Rub21** [comment]
> I think the task is ready to hit

Nice!

## Next action:

- [ ] @rub21 add `missingOneway` validator in connectivity linting. This  will detect every two days.
- [ ] @planemad  create a master ticket to start working on these issues.

**Comment by Rub21** [comment]
@planemad ^^

**Comment by Rub21** [comment]
@planemad  still missing a master ticket to start working on this task - http://osmlab.github.io/to-fix/#/task/missingonewaysmotorwaylink, can you create it.?

**Comment by Rub21** [comment]
done!
