### ISSUE TITLE
Falsos Positivos - Missing Layer  

### ISSUE THREAD

**Issue by ridixcr** [osmlab/osmlint#132]
Tofix Muestra tareas donde el atributo es layer=no 
![falsos positivos-mising layer](https://cloud.githubusercontent.com/assets/1646072/16694443/ed1f8438-44ff-11e6-83d4-42b867dfd0ee.png)

también cuando en su histórico tiene el atributo layer=no también los detecta como tarea valida

**Comment by Rub21** [comment]
fixed!
