### ISSUE TITLE
Missing layer bridges and  waterway with layer=-1

### ISSUE THREAD

**Issue by calfarome** [osmlab/osmlint#137]
While we are working on tasks [missinglayerbridges](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor) and  [highwayintersectswater](http://osmlab.github.io/to-fix/#/stats/highwayintersectswatermajor) many times we find the following two cases.

#### 1. Bridges without layer and  waterway with  layer= -1.

https://www.openstreetmap.org/way/156162668/history
![b1](https://cloud.githubusercontent.com/assets/10413117/16775331/bbcc4014-4825-11e6-9fc4-0c1c110cf4dc.gif)

#### 2. According to the image there is a bridge, but the waterway has layer = -1.

https://www.openstreetmap.org/way/156294430/history
![b2](https://cloud.githubusercontent.com/assets/10413117/16775714/9b7535b2-4827-11e6-9336-60f9f3348603.gif)

##### What actions we take in these cases mentioned?.
cc. @Rub21

**Comment by samely** [comment]
@calfarome this should be in /data repo, and tag the data-team.
