### ISSUE TITLE
¿Qué hacer en estos casos?

### ISSUE THREAD

**Issue by piligab** [osmlab/osmlint#138]
¿Cuál es la correcta solución a este error que nos da la tarea de broken polygons?

![screenshot from 2016-07-13 09-43-45](https://cloud.githubusercontent.com/assets/19536044/16807547/83ca1df8-48de-11e6-9b27-02424cd4d089.png)

@Rub21

**Comment by Rub21** [comment]
por el momemnto no sera bueno solucionar esos errores, he reparado el codigo par auqe evite esas deteciones.
