### ISSUE TITLE
[Validator] Misspelled tags

### ISSUE THREAD

**Issue by samely** [osmlab/osmlint#145]
Some objects seem to be misspelled tagged, just as an example `higway=*` instead of `highway=*`
[Keepright](http://keepright.at/)

cc. @Rub21 @aaronlidman @planemad

**Comment by Rub21** [comment]
@samely  Estoy de acuerdo en que se debe implementar este validador!

**Comment by samely** [comment]
I've added this validator and test https://github.com/osmlab/osmlint/tree/misspelled. you can also see the data in http://osmlab.github.io/to-fix/#/task/mispelledtags

**Comment by samely** [comment]
@Rub21  I've updated the [validator](https://github.com/osmlab/osmlint/tree/misspelledtags) with your suggestions.
About value_area.js. I just considered adding main tags from http://wiki.openstreetmap.org/wiki/Map_Features. And I also added some tags like  `tower:*` or `ship:*` which I referenced and don't have documentation, however, many objects have those tags.

**Comment by samely** [comment]
Done
