### ISSUE TITLE
Increase the angle in impossibleAngle

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#149]
Currently, we are detecting angles < 10 ,  we should increase this to < 30
https://github.com/osmlab/osmlint/blob/58af4bdc396146499c50537f598e508b25994964/validators/impossibleAngle/map.js#L62

cc. @maning @planemad

**Comment by planemad** [comment]
@Rub21 it would be good to document the reasoning to choose 30 degrees? Any examples?

**Comment by Rub21** [comment]
@planemad  By now the is no way to select this kind of attributes in osmlint, however, make a documentation would be great! can someone from the team can help us on that?

cc. @samely

**Comment by Rub21** [comment]
close for now this!
