### ISSUE TITLE
Callback to function should be passed data instead of needing to read stdout

### ISSUE THREAD

**Issue by batpad** [osmlab/osmlint#17]
Right now, as per the docs:

```
    // Outputs nodes with bridge tags to stdout
require('osmlint').bridgeOnNode([-122.1, 36.9, -121.9, 37.0], 15, './osm.mbtiles', function() {
    console.log('done');
});
```

I would expect the callback `function()` there to receive something like `data` with the invalid features rather than needing to read `stdout`.

**Comment by lxbarth** [comment]
None of the validators aggregate features right now ([example](https://github.com/osmlab/osmlint/blob/master/validators/bridgeOnNode/index.js#L17)) but rather write feature by feature to stdout to save memory. This makes sure they scale.

We could make aggregation optional like so:

    require('osmlint').bridgeOnNode(
        [-122.1, 36.9, -121.9, 37.0],
        15,  true /* means aggregate! */,
        './osm.mbtiles', function(geojson) {
        console.log(geojson);
    });

**Comment by Rub21** [comment]
@batpad @lxbarth : 

I've implemented the requirement on this issue : https://github.com/osmlab/osmlint/commit/4a082eef2ee58698aa7d7d5691d6af411a8bd785
 
to add the options  like here: https://github.com/osmlab/osmlint/blob/dev/test/test.aggregate.js#L12-L16,  the test.aggregate.js works fine.

For cli, https://github.com/osmlab/osmlint/commit/41c9bdf480c7e014a7523bf095301f77cf0edd0b

### Next action

- [ ]  @batpad  can you do a quick revision? 
- [ ] @rub21 merge.

cc. @geohacker

**Comment by geohacker** [comment]
@Rub21 - thank you for taking a stab. Though, this seems slightly inefficient to me. We are writing the feature to stdout **as well as** returning the feature back to the main script. The behavior I'm imagining is:

1. the `map` script always `return` a Feature to the main script.
2. main script always `return` a FeatureCollection 
3. `cli.js` sends a callback, and writes the FeatureCollection to stdout.

@batpad thoughts?

**Comment by batpad** [comment]
I think the explanation of why the validators just write to `stdout` and don't return makes total sense. I'm not sure adding the option to return is worth the over-head.

Writing to `stdout` and returning values is definitely going to be inefficient and we should avoid. We could add an option to either write to `stdout` OR return, but I would really punt on that.

In my mind, the ideal option would be something like being able to pass a Writeable Stream object to the validator that gets written to. This could be `stdout` or any writeable stream like object, I would punt on this for now though. @geohacker do you want to just close this?

**Comment by geohacker** [comment]
Sounds good. We can revisit.
