### ISSUE TITLE
[Validator] Missing junction=roundabout 

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#173]
![image](https://cloud.githubusercontent.com/assets/1152236/20482545/31794418-afbb-11e6-80a3-4270fca90281.png)
https://www.openstreetmap.org/way/451480864/history#map=19/-12.11739/-76.96494

**Comment by dannykath** [comment]
:+1:

**Comment by Rub21** [comment]
done!!  thank @dannykath !!
