### ISSUE TITLE
opts = {}

### ISSUE THREAD

**Issue by lxbarth** [osmlab/osmlint#18]
We should wrap options into an object to make the function signature of validators extensible. This discussion here made me think of that: https://github.com/osmlab/osmlint/issues/17#issuecomment-165680200

So instead of 

    validators.bridgeOnNode(bbox, zl, mbtilesPath, callback);

we should do:

    validators.bridgeOnNode({bbox: bbox, zl: zl}, mbtilesPath, callback)

which allows for future additional parameters without breaking the function signature:

    validators.bridgeOnNode({bbox: bbox, zl: zl, aggregate: true}, mbtilesPath, callback)

Parameters in the options object should be in line with options on the command line:

    osmlint bridgeonnode --bbox="[1, 2, 3, 4]" --zoom=15 --aggregate osm.mbtiles

**Comment by Rub21** [comment]
@lxbarth @geohacker :
I've implemented this requirement. 

two commits: 
- https://github.com/osmlab/osmlint/commit/22fde63256416082e6f31c307e0abef51eaab116
- https://github.com/osmlab/osmlint/commit/f1810215cfee18d116d51a656a86d97ce6b10fdb

The test passing fine and on /peer-review(CLI) as well. 

### Next action

- [ ] @geohacker  fast checkout 
- [ ] @rub21 master to master.
