### ISSUE TITLE
Checking self-intersecting and unconnected validators

### ISSUE THREAD

**Issue by samely** [osmlab/osmlint#181]
Since we have many [changeset comments](https://github.com/mapbox/mapping/issues/203#issuecomment-263701125) about splitting objects that shouldn't be considered as errors, we decided not taking action about them. But also we will spend time marking them as `not an error`. So we need to improve validators for those tasks.

cc. @Rub21 @calfarome

**Comment by planemad** [comment]
Agree that we should ignore way that end back at itself but do not cross. Does this make sense? or are we ignoring all?

![blank](https://cloud.githubusercontent.com/assets/126868/20826186/26d43842-b88f-11e6-9453-ba59b5d6145c.png)

**Comment by Rub21** [comment]
this si done!!
