### ISSUE TITLE
[Validator] Detect private source on objects

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#184]

**Comment by Rub21** [comment]
great job here https://github.com/osmlab/osmlint/pull/196 @karitotp .

@maning @planemad  @geohacker  what do you think to upload this detection to to-fix? 
example: https://gist.github.com/anonymous/082afb47aa454348b75c1bb1dd392878

**Comment by maning** [comment]
@karitotp @Rub21 Can you explain more what do we mean by private source?  The sample shows one with a tag source=google but I'm not sure about the others.

**Comment by karitotp** [comment]
@maning  reviewing some wikis such as [WikiProject Malaysia](http://wiki.openstreetmap.org/wiki/WikiProject_Malaysia#Forbidden_data_sources), I found these private sources to add objects to OSM

**Comment by maning** [comment]
I see.  This is great!   Made some [minor comments](https://github.com/osmlab/osmlint/pull/196/files#diff-89298a5c991d28f50613fa333c09bae4R8) on the code.  Over to @geohacker .

**Comment by Rub21** [comment]
I've fixed the minor issues here, I think we are ready to merge..?

**Comment by geohacker** [comment]
@Rub21 - this is still looking for an exact match. What if the source tag in the feature was something like `google earth` or `Google earth`? Can we make them case insensitive? May be use a regular expression so we can catch a [wide range of combinations](https://github.com/osmlab/osmlint/pull/196#issuecomment-277157089)?

**Comment by Rub21** [comment]
done here https://github.com/osmlab/osmlint/pull/196!!
