### ISSUE TITLE
Quitar `aeroway=apron`

### ISSUE THREAD

**Issue by dannykath** [osmlab/osmlint#186]
@Rub21 puede quitar de las detecciones de [Broken Polygons](https://osmlab.github.io/to-fix/#/task/brokenpolygonsgkvy) el tag `aeroway=apron`, 
 
![ejemplo](https://cloud.githubusercontent.com/assets/8483644/21278612/41323ad8-c3aa-11e6-8e00-ccadfd0eadcd.png)

**Comment by Rub21** [comment]
@samely  can you handle this?

**Comment by samely** [comment]
@Rub21 I've [removed](https://github.com/osmlab/osmlint/pull/193) this tag.

**Comment by samely** [comment]
This tag has been removed from detection.
