### ISSUE TITLE
filterDate validator should take start and end date

### ISSUE THREAD

**Issue by geohacker** [osmlab/osmlint#20]

**Comment by Rub21** [comment]
@geohacker .  I think to solve this issues we have two options:

- Passing the the start  a end date to `map.js` but now it is not possible https://github.com/mapbox/tile-reduce/issues/48

- Create a file where save the parameters (start and end date) when `index.js` started and before tilereduce function started.  and the call this file in `map.js`

for now the second is the best option, what do you think?

**Comment by geohacker** [comment]
@Rub21 - let's punt here until there's a new release of tile-reduce.

**Comment by Rub21** [comment]
for now no action here! close
