### ISSUE TITLE
name=noname

### ISSUE THREAD

**Issue by mtmail** [osmlab/osmlint#214]
Similar to null values (https://github.com/osmlab/osmlint/issues/157) I'll add looking for 'noname' and 'no-name' (case-insensitive). 

Examples:
http://www.openstreetmap.org/way/39864464
http://www.openstreetmap.org/way/63467130
http://www.openstreetmap.org/way/338318718

Of course there's always the chance somebody named their restaurant or mountain peak really 'noname' to be funny.

**Comment by Noznoc** [comment]
Validator complete [here](https://github.com/osmlab/osmlint/tree/master/validators/noName)
