### ISSUE TITLE
OSMLint validator for self intersecting line based water features

### ISSUE THREAD

**Issue by manoharuss** [osmlab/osmlint#223]
Example:

![image](https://cloud.githubusercontent.com/assets/8921295/25123945/cf30c8d8-2447-11e7-90b8-659e3407b101.png)

_[Link](https://www.openstreetmap.org/changeset/47885621)_

- Pokemon mappers on OSM map wide variety of features like water bodies, parks, meadows and recreation grounds.
- Catching self intersecting line based water features should be pretty easy, to catch randomly mapped objects like in the example above.

Few examples of line based water features:
`waterway=river`
`waterway=stream`
`waterway=canal`
`waterway=drain`

cc @Rub21 @planemad @geohacker @krishnanammala @batpad

**Comment by Rub21** [comment]
done https://github.com/osmlab/osmlint/pull/228!!
