### ISSUE TITLE
Finding missing turn links at intersections

### ISSUE THREAD

**Issue by planemad** [osmlab/osmlint#231]
How can we find missing turn links between major roads like these? Such missing links can increase the route distance at the turn by upto 50% compared to the actual driving distance.

A good algorithm to quickly find such missing links based on road classes and intersection angles can help create to-fix tasks for data improvement.

<img width="647" alt="screen shot 2017-06-05 at 11 33 52 am" src="https://cloud.githubusercontent.com/assets/126868/26772446/12975b8a-49e3-11e7-8293-4616be47b90c.png">

<img width="375" alt="screen shot 2017-06-06 at 3 37 28 pm" src="https://cloud.githubusercontent.com/assets/126868/26824226/1f2a57bc-4ace-11e7-96c8-69b33dbf6887.png">

<img width="293" alt="screen shot 2017-06-06 at 3 37 46 pm" src="https://cloud.githubusercontent.com/assets/126868/26824227/1f77f058-4ace-11e7-936d-80ba732ea487.png">

cc @Rub21 @dannykath @srividyacb @jothirnadh @maning

**Comment by planemad** [comment]
- Free turn links are more common on wider roads with high traffic
- Turn links are created to reduce the sharpness of a turn for a car

**Comment by daniel-j-h** [comment]
For context: OSRM recognizes these turn links as sliproads and issues better guidance instructions here. Having these turn links mapped therefore will not only lead to better routing but also to better guidance instructions.

**Comment by Rub21** [comment]
@planemad @daniel-j-h I spent few hours doing this, but the detector is getting many false positives. https://github.com/osmlab/osmlint/tree/turnlinks/validators/missingTurnLinks ,
@daniel-j-h  maybe do you have some ideas to improve it, I am still thinking to do it better.

**Comment by daniel-j-h** [comment]
Not sure you can detect these on the planet in general without many false positives. In germany you'd for example expect there to be a traffic signal at the main intersection, a sign or a traffic signal before the sliproad, in right-sided driving countries the turn to go right onto a street, etc. - using angles alone is too ambiguous.

**Comment by planemad** [comment]
Since these links are more important on wide roads, maybe we could get better results if we limit the input set?

- Intersection of only roads of class: trunk, primary, secondary, tertiary 
- Roads more than 4 lanes wide total (`lanes`>=4, `lanes:forward`+`lanes:backward`>=4)

@Rub21 also would be great to review the output for ideas, could you load it into to-fix?

**Comment by Rub21** [comment]
@planemad @daniel-j-h :  I fixed according:
> Intersection of only roads of class: trunk, primary, secondary, tertiary
Roads more than 4 lanes wide total (lanes>=4, lanes:forward+lanes:backward>=4)

There are still too many false positive, check here 👇 

https://gist.github.com/anonymous/bf581bbc1b07c0e706a6d65e8be4ed70

I will close this ticket until to get another way to detect that issue.
