### ISSUE TITLE
Validator for separator token in tags

### ISSUE THREAD

**Issue by daniel-j-h** [osmlab/osmlint#233]
Semicola `;` can be used as a separator for multiple values.
In case of lane tags a pipe `|` can be used to represent lane-specific values:

- http://wiki.openstreetmap.org/wiki/Semi-colon_value_separator
- http://wiki.openstreetmap.org/wiki/Multiple_values

Can we write validators flagging mis-uses such as [this](http://www.openstreetmap.org/way/31129372)

    destination=Harrison Street|Embarcadero

for lane pipes in tags without lanes and no lane pipes in tags representing lanes?

I assume there are even more cases of separator token mis-uses - is there any work on this already?

cc @srividyacb

**Comment by Rub21** [comment]
@dannykath  could you work on this, if you have questions let me know.

**Comment by dannykath** [comment]
@Rub21  https://github.com/osmlab/osmlint/pull/241

**Comment by Rub21** [comment]
Good work @dannykath !!

@daniel-j-h :

 I was checking the output  for US and Germanny:

- [US](https://gist.github.com/anonymous/2710c3c987ebdb08597a5673c2eca2ed): 17 issues
- [Germany](https://gist.github.com/anonymous/73a3b8931cacbece6fcfa97153257fe1) :134 issues

 how can we fix in this cases?

Case1: https://www.openstreetmap.org/way/279936025/history

`destination=East I 285;Augusta;Greenville|East I 285;Augusta;Greenville|East I 285;Augusta;Greenville|I 75;Atlanta;Macon;Tampa|I 75;Atlanta;Macon;Tampa`


And also there is othere tag which maybe needs to fix? 

`destination:lanes=Augusta;Greenville|Augusta;Greenville|Augusta;Greenville|Atlanta;Macon;Tampa|Atlanta;Macon;Tampa`
`destination:ref:lanes=East I 285|East I 285|East I 285|I 75|I 75`


Case 2: https://www.openstreetmap.org/way/276800564/history

`destination=A|A|B`

it  :point_up:  does not have sense,  shall we fix too? 

cc.@srividyacb

**Comment by srividyacb** [comment]
We have been learning how to map destination and exit tags in OpenStreetMap fro @1ec5 . Per our talk : 

- Only `turn:lanes`, `destination:lanes` and `destination:lanes` tags in OpenStreetMap should have pipe as separator between different values and no other tag combination should contain `|` in them.
- So `destination`, `destination:street` and `destination:ref` tag should not have `|` in them. 

@Rub21 Based on the examples you have specified - 

> `destination=East I 285;Augusta;Greenville|East I 285;Augusta;Greenville|East I 285;Augusta;Greenville|I 75;Atlanta;Macon;Tampa|I 75;Atlanta;Macon;Tampa`

- In the above senarios, this should be fixed.

> `destination:lanes=Augusta;Greenville|Augusta;Greenville|Augusta;Greenville|Atlanta;Macon;Tampa|Atlanta;Macon;Tampa`
`destination:ref:lanes=East I 285|East I 285|East I 285|I 75|I 75 `

- In the above scenario there is no need to fix.

cc @maning @jothirnadh @manoharuss @dannykath

**Comment by dannykath** [comment]
@srividyacb I have added to 2 conditions to check 2 tags in the validator, so the detection is complete for US and Germany 
I have added 2 task in https://hey.mapbox.com/to-fix/

- Detection for [US](https://hey.mapbox.com/to-fix/#/task/separatortokenintagsus)
- Detection for [Germany](https://hey.mapbox.com/to-fix/#/task/separatortokenintagsgermany)

Could you please try fix using these tasks :point_up_2: 
Is it possible if we start to clean up in 2 cities
@Rub21  Could you check the validator and if is possible could you merge to master?

**Comment by dannykath** [comment]
@srividyacb  Could you try 2 validators? :pray: 
Is it possible if Peru team work on this task?
cc. @Rub21

**Comment by Rub21** [comment]
This validator was created  done 
 here!! https://github.com/osmlab/osmlint/tree/master/validators/separatorTokenDestination, close here!!
