### ISSUE TITLE
Validator for invalid turn restrictions

### ISSUE THREAD

**Issue by daniel-j-h** [osmlab/osmlint#236]
(I haven't found a validator for this - if we already have one in place feel free to close this)

For turn restrictions of the form `(fromWayId, viaNodeId, toWayId)` the `viaNodeId` needs to connect the way `fromWayId` to the way `toWayId`. Turn restrictions where the via node is not shared across the two ways are invalid.

Our routing engine filters via-node turn restrictions that are invalid and discards them. We should have a validator in place since this type of error should be easy to detect and fixing it is of high value for routing.

---

Related to that - turn restrictions have a well-defined format:

http://wiki.openstreetmap.org/wiki/Relation:restriction#Members

the relation members have to be:
- `from` - of type `way`, exactly 1 way, except can be multiple ways only when `no_entry` restriction!
- `to` - of type `way`, exactly 1 way, except can be multiple ways only when `no_exit` restriction!
- `via` - either a single `node` or multiple `ways`

We should have a validator in place for checking all turn restrictions making sure they conform to this schema.

cc @srividyacb @Rub21

**Comment by srividyacb** [comment]
This is a must validator to have. Based on my knowledge - we use OSM-QA tiles and tile-reduce for most of the linters scripts to detect tagging and connectivity errors. But I don't think OSM-QA tiles have turn-restriction in it. 

@Rub21 how can we build this validator?

cc @daniel-j-h

**Comment by planemad** [comment]
@ramyaragupathy have we ever made a global tileset of turn restrictions?

**Comment by ramyaragupathy** [comment]
Nope, but this can be done with osmlazer @planemad

**Comment by daniel-j-h** [comment]
Flagging: there is also an edge case with `no_entry` and `no_exit` which we stumbled upon lately

https://github.com/Project-OSRM/osrm-backend/issues/4241

and our routing engine does not handle it yet. It's on our feature list to implement.

What's interesting in the context of validators is @mokob sampled the OpenStreetMap data for `no_entry` and `no_exit` and found quite a few issues with how they're getting used and simple mis-uses. At the moment there are only a couple hundreds `no_entry`s and `no_exit`s in the dataset - it could make sense to check them, too.

**Comment by Rub21** [comment]
@daniel-j-h , I thought this could be possible using the Multipolygon mbtiles that have been in the test(this contain some relations)  but not, it does not contain the TR relations.

@ramyaragupathy could we get TR data from osmlazer as geojson? 
@daniel-j-h , Maybe do you know other ways to get these TR data as geojson?  

if it so, we could use the geojson to combine with the osm-qa-tiles to do the analysis and detect those invalid TR.

**Comment by ramyaragupathy** [comment]
>could we get TR data from osmlazer as geojson?
Nope, only the count works @Rub21

**Comment by ramyaragupathy** [comment]
Worked w/ @planemad to expand on [earlier work of grouping relations](https://github.com/ramyaragupathy/group-relations/tree/tr). Script here regroups relations by their ID & append member geometries to each relation in a [GeometryCollection](https://geojson.org/geojson-spec.html#geometry-collection). 

We ran it against TRs in SF & got the geojson formatted to represent relations as Geometry Collection. Contents are shared in [dropbox](https://www.dropbox.com/sh/hvmmq6v5qoe98aw/AABIOyVIchtZsn8MIPoqJ1OLa?dl=0).
- the input file  `SFTR_Input.geojson`
- output file `SFTR_reorganised.geojson` & `output.mbtiles`

_[Interactive map](http://ramyaragupathy.github.io/group-relations/#17.52/37.75923/-122.46529)_

### More on the data structure

[Sample file of a TR as GeometryCollection](https://gist.github.com/anonymous/c8ac1d9130264d9426e2b2d445a8ab5a).

All relation related properties at feature level:

```
"properties": {
    "type": "restriction",
    "restriction:type": "no_left_turn",
    "restriction:id": 6191617,
    "members": [
      {
        "label": "from"
      },
      {
        "label": "via"
      },
      {
        "label": "to"
      }
    ]
  }
```

`members` array within `properties` store info on each role that constitutes a TR.
Order within the member array matches the geometry order within `geometries` array of a feature.

cc @Rub21 @daniel-j-h @srividyacb @maning

**Comment by Rub21** [comment]
@ramyaragupathy  This is nice!! the mbtiles works fine!! , I am doing some analysis to detect invalid TR,  but I could not find to any of this in SF, could you create a  mbtiles for US?

**Comment by geohacker** [comment]
@ramyaragupathy nice work! the output.mbtiles you posted above doesn't seem to have any GeometryCollections. Is that right? 

@Rub21 @ramyaragupathy @planemad - just want to flag that Tile Reduce does not support [GeometryCollections](https://github.com/mapbox/tile-reduce/issues/104), unfortunately, which means OSMLint may not work. We [have tried this before.](https://github.com/mapbox/tile-reduce/issues/88)

**Comment by ramyaragupathy** [comment]
Looks like tippecanoe just treats each geometry within the `GeometryCollection` as a separate feature, instead of treating all the geometries as an unit @geohacker @planemad @Rub21 

Thinking of osmium here. For relations, though it does not return the geometry data, it contains details that can be used to generate geometries:

```
{ restriction: 'only_right_turn', type: 'restriction' }
[ { type: 'w', ref: 478760157, role: 'from' },
  { type: 'n', ref: 176581223, role: 'via' },
  { type: 'w', ref: 61840757, role: 'to' } ]

```

From the id's, geometries can be obtained and then linters could be run in the same script for validation.

**Comment by ramyaragupathy** [comment]
yeah the workflow will be different from the existing ones @geohacker

**Comment by Rub21** [comment]
Because  mbtiles does not support relation, we created another report to detect  invalid relations  https://github.com/osmlab/osmlint-osmium/tree/master/validators

Close this ticket here!!
