### ISSUE TITLE
[Validator] Crossing buildings

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#24]
cc . @geohacker @maning

**Comment by maning** [comment]
Lets make this more generic to overlapping polygons/closed ways.  For example, for polygons/closed ways with the same kv pair (`landuse=*`, `building=*`, `natural=*`), check for overlaps.

Lets ignore multipolygons relations for now.

@geohacker @planemad @Rub21

**Comment by planemad** [comment]
Yes, the crossing linter should accept a list of keys: ["landuse", "building", "natural"] and produce the overlapping objects.

 @maning any particular scenario for which you think we need to compare tag values as well?

**Comment by maning** [comment]
Generally, same key should not overlap.  But there are edge cases, i.e. amenity=something within amenity=parking.  Let's avoid catchall detectors.  We can fine tune detectors as we encounter them.

**Comment by Rub21** [comment]
@aaronlidman @geohacker  @morganherlocker  , Could you  help me here ,https://github.com/osmlab/osmlint/blob/crossingbuildings/validators/crossingBuildings/map.js

so, i am trying to do validator for crossing buildings,  i am using ` turf.intersect`,  but it throws error  for [monaco.mbtiles](https://github.com/osmlab/osmlint/blob/crossingbuildings/test/fixtures/monaco.mbtiles),  and work for [peru.mbtiles](https://s3.amazonaws.com/mapbox/osm-qa-tiles/latest.country/peru.mbtiles.gz). we are using monaco.mbtiles for testing.

other problem is: 
- some of the [result for Peru](https://gist.github.com/anonymous/e5767cac6007fbfb0646) are  false positive:( , so I think, it is because  in zoom 12 osm-qa-tiles changes the coordinates of some buildings and it were detected in overlap, but in OSM are ok.

Perhaps, Could you recommend  other ways to do  this detection?

**Comment by Rub21** [comment]
Per chat with @aaronlidman , here is the geojson of [Monaco buildings](/home/ruben/Dropbox (Mapbox)/Public/monaco.geojson.zip)

**Comment by Rub21** [comment]
@maning  a result from crossing buildings, https://gist.github.com/anonymous/42958ff767c141b20d98,
 to geenerate the result, it take around 40 min ,   I modified quiet bit but still give a error and is slow. https://github.com/osmlab/osmlint/blob/crossingbuildings/validators/crossingBuildings/map.js :(

**Comment by maning** [comment]
@Rub21 Checked a few (12 buildings) from your sample data all are confirmed crossing buildings. Yay!  

We need to formalize what tags should be included.  I don't think it should be this way, 
`properties":{"way1":169254869,"way2":169254828}`.  Lets make each error as one object similar to other **validators/analyzers/linters/processors** (can we decide on what to call them?) and add the other OSM tags and metadata. Related ticket: https://github.com/osmlab/osmlint/issues/30

@geohacker, can you :eyes: at the code?  Intersection functions are always expensive, we may need some refactoring on this one.

**Comment by geohacker** [comment]
@Rub21 questions - 

1. This filter removes buildings that self intersect. https://github.com/osmlab/osmlint/blob/crossingbuildings/validators/crossingBuildings/map.js#L9-L16 Why?
2. Why do you change the geometry type to LineString here? - https://github.com/osmlab/osmlint/blob/crossingbuildings/validators/crossingBuildings/map.js#L13-L14 
3. All objects in `buildings` are of type LineString, but [turf.intersect](http://turfjs.org/static/docs/module-turf_intersect.html) takes two Polygons and returns a Polygon, undefined or MultiLineString. In which case I think [this line](https://github.com/osmlab/osmlint/blob/crossingbuildings/validators/crossingBuildings/map.js#L24) will fail?

I think the reason why this is slow is because of the [loop](https://github.com/osmlab/osmlint/blob/crossingbuildings/validators/crossingBuildings/map.js#L19). For every building it loops through the entire set of buildings. 

Ideas to consider - we don't have to compare every building to every other building in the set. We can limit this by a distance threshold. We are only interested in comparing buildings that are close enough:

1. Check the distance between the buildings (their centroids) and if they are < ~10 meters apart then do the intersection. Assuming that finding distance is cheaper than calculating intersection.
2. Slightly ambitious and not sure if this would work - calculate a distance matrix for all buildings in the tile and check for combinations that are within ~10m.

**Comment by Rub21** [comment]
@geohacker :

> This filter removes buildings that self intersect. https://github.com/osmlab/osmlint/blob/crossingbuildings/validators/crossingBuildings/map.js#L9-L16 Why?

I got an error : https://github.com/osmlab/osmlint/issues/29, for that  I've  considered avoid the self-intersect Polygons  , maybe we can do this detection for other validator. 

> Why do you change the geometry type to LineString here? - https://github.com/osmlab/osmlint/blob/crossingbuildings/validators/crossingBuildings/map.js#L13-L14

For polygons, it give us more errors than Linestring, and also give me rare polygon with just two coordinates, it can be sound strange but i saw it, and give many false positive as well.  for that I preferred change to Linestrig, even in Linestring, we can get the exact intersection and it should be more easy to detect where is the overlap. 

> All objects in buildings are of type LineString, but turf.intersect takes two Polygons and returns a Polygon, undefined or MultiLineString. In which case I think this line will fail?

`turf.intersect` is  working for Linestring as well. 

> Check the distance between the buildings (their centroids) and if they are < ~10 meters apart then do the intersection. Assuming that finding distance is cheaper than calculating intersection.

Yeah, maybe it can be work, but we have to compare the distance for entire set of buildings as well. 

> Slightly ambitious and not sure if this would work - calculate a distance matrix for all buildings in the tile and check for combinations that are within ~10m.

This sound interesting can you give me more context about this.

**Comment by morganherlocker** [comment]
> Ideas to consider - we don't have to compare every building to every other building in the set. We can limit this by a distance threshold. We are only interested in comparing buildings that are close enough

I would consider a spatial index here like [rbush](https://github.com/mourner/rbush). This will speed up processing dramatically and with full precision.

**Comment by geohacker** [comment]
> For polygons, it give us more errors than Linestring, and also give me rare polygon with just two coordinates, it can be sound strange but i saw it, and give many false positive as well. for that I preferred change to Linestrig, even in Linestring, we can get the exact intersection and it should be more easy to detect where is the overlap.

@Rub21 Not sure if I understand this. Do you have an example? Outright it seems wrong me to change the geometry type of a feature.

**Comment by Rub21** [comment]
@geohacker @batpad @maning : 
I just improved a bit this crossing building validator. https://github.com/osmlab/osmlint/commit/9d4435c30430c3d540478cf88366a42714693840
results: 
- [Peru](https://gist.github.com/anonymous/8c1f6ca9cbb1b26629cd) , time to process : 3.30 min
- [Monaco](https://gist.github.com/anonymous/b3f361c199534814a886),  time to process : 43 sec.

I got some false positive. it is because the data in osm-qa-tiles at zoom 12 the shapes change a little bit.

**Comment by Rub21** [comment]
rbush is amazing!! , now the crossing building validator is hundred times faster,  it processing really fast the crossing buildings. 

- [Peru](https://gist.github.com/anonymous/e9c9c9e394aa92762201)  19 sec. 
- [Monaco](https://gist.github.com/anonymous/66976ee636f5cc1ee772) 11 sec.

## Next acction :

- [ ] Time to Merge https://github.com/osmlab/osmlint/pull/41

Thanks @morganherlocker for the advice.

**Comment by maning** [comment]
I'm seeing many false-positives.

Building properly connected

![screen shot 2016-01-20 at 14 53 41](https://cloud.githubusercontent.com/assets/353700/12444566/abd8b9ae-bf85-11e5-9fdb-dc0db6832cb9.png)

Very close, but no overlap (refer to the scalebar UL corner)

![screen shot 2016-01-20 at 14 51 06](https://cloud.githubusercontent.com/assets/353700/12444567/abdc538e-bf85-11e5-86b9-0178b5aaeb96.png)

![screen shot 2016-01-20 at 14 45 51](https://cloud.githubusercontent.com/assets/353700/12444568/abddfb44-bf85-11e5-90b6-ca2e6963abda.png)

![screen shot 2016-01-20 at 14 45 04](https://cloud.githubusercontent.com/assets/353700/12444569/abdf2c3a-bf85-11e5-89d7-f3879a2be030.png)

**Comment by morganherlocker** [comment]
> I'm seeing many false-positives.

@maning Can you post some of the geometries so these can be made into test fixtures?

**Comment by Rub21** [comment]
@morganherlocker  one of the false-positive: https://gist.github.com/anonymous/f91b3f96800657dbf715
- https://www.openstreetmap.org/way/366601454/history
- https://www.openstreetmap.org/way/366601464/history

 in JOSM:
![image](https://cloud.githubusercontent.com/assets/1152236/12453865/22490828-bf63-11e5-868c-7fe5d094100c.png)

In osm-qa-tiles change the geometry and the validator detected it as error. 

we can avoid those false-positive increasing  the number of are `(area > 0.4)`  to 1.2. but many other errors are avoided as well 
https://github.com/osmlab/osmlint/blob/crossingbuildings/validators/crossingBuildings/map.js#L32

**Comment by maning** [comment]
@Rub21 any status on this? I would like to run this for linting labuildings.

**Comment by maning** [comment]
@geohacker @Rub21 @arunasank Can we do this? Context here: https://github.com/osmlab/labuildings/issues/92#issuecomment-222731623

**Comment by Rub21** [comment]
The problem here was  with the `mbtiles` in zoom 12,  this should be working better for mbtiles upper zoom 15. Close Here!

**Comment by maning** [comment]
@Rub21 Would [difference](http://turfjs.org/docs.html#difference) work better than [intersect](https://github.com/osmlab/osmlint/blob/crossingbuildings/validators/crossingBuildings/map.js#L29)?

cc/ @geohacker

**Comment by Rub21** [comment]
@maning  since we really need this validator for LA, I will figure out again to detect this issues, and thank you for your suggestion.

**Comment by Rub21** [comment]
ready here https://github.com/osmlab/osmlint/pull/205!!!
