### ISSUE TITLE
[Validator] Self-intersecting highways

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#25]
Done! https://github.com/osmlab/osmlint/tree/self-intersecting
result : https://gist.github.com/anonymous/20c970b25e75d4011895.

@planemad @maning is right detect this kind of [way](http://www.openstreetmap.org/way/176334440) as a Self-intersecting highways?

cc. @geohacker

**Comment by maning** [comment]
Checked a few of your results.  They are not self-intersecting ways.  This is what we should detect:
![screen shot 2016-01-05 at 09 51 45](https://cloud.githubusercontent.com/assets/353700/12107537/65effa3c-b392-11e5-9b14-d90102e124ed.png)

**Comment by Rub21** [comment]
I've fixed the validator, the result is : https://gist.github.com/anonymous/9deede952e9867174804, it looks fine .

### Next Action

- [ ] Merge the branch [self-intersecting](https://github.com/osmlab/osmlint/tree/self-intersecting) to master

cc @geohacker

**Comment by maning** [comment]
@Rub21, checked and confirmed this is the expected result.  Good job!

**Comment by Rub21** [comment]
done!
