### ISSUE TITLE
[Validator]Unclosed ways for area features 

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#26]
from : https://github.com/mapbox/peer-review/issues/2
I am trying to detect all [enclosed ways](https://github.com/osmlab/osmlint/blob/unclosedways/validators/unclosedWays/map.js#L8) in OSM. but  on the result  [I got incomplete ways ](https://gist.github.com/anonymous/2c084959620216692516), I've checked out those objects in OSM  those  are complete ways ,  I think  it happen when the tile-reduce clip the objects to bbox of tile. 

my question here,is there a way to avoid  the incomplete ways? or should i do manually?, checking out the bbox of tile?

here the [map.js](https://github.com/osmlab/osmlint/blob/unclosedways/validators/unclosedWays/map.js)

cc. @aaronlidman @mourner @morganherlocker  @geohacker

**Comment by mourner** [comment]
I'd say you can't avoid incomplete ways if you slice the data into tiles. I would suggest writing a custom script that reads an OSM.PBF file directly (e.g. using https://github.com/substack/osm-pbf-parser).

**Comment by morganherlocker** [comment]
One thing you may be able to do is add a pixel buffer to your tiles. If you find an unenclosed way, check to see if it overlaps with the tile buffer. If it does, you can either report "unknown" (easy) or you can recursively crawl more tiles along the hull of the polygon (hard). If you give yourself a large enough pixel buffer, you might actually be able to find most of the cases you are looking for. There are a couple more options, but they involve some bad hacks.

**Comment by Rub21** [comment]
Thank you for the advice.
I made quiet similar  to :

> One thing you may be able to do is add a pixel buffer to your tiles. If you find an unenclosed way, check to see if it overlaps with the tile buffer. If it does, you can either report "unknown" (easy)

https://github.com/osmlab/osmlint/commit/591f8adaa8800e8e13ab828bb4924509d8377620

Now it is working fine.
