### ISSUE TITLE
[Validator] Evaluate unclosed ways for area features

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#28]
I have some progress on this validator: https://github.com/osmlab/osmlint/tree/591f8adaa8800e8e13ab828bb4924509d8377620/validators/unclosedWays
 but we have to evaluate : 
- http://wiki.openstreetmap.org/wiki/Key:aeroway (Features Point , LineString, Polygon)
- http://wiki.openstreetmap.org/wiki/Key:landuse (Features Point and Polygon)
- http://wiki.openstreetmap.org/wiki/Key:leisure (Features Point , LineString, Polygon)
- http://wiki.openstreetmap.org/wiki/Key:natural (Features Point , LineString, Polygon)
- http://wiki.openstreetmap.org/wiki/Key:highway (Features Point , LineString, Polygon) on this case evaluate with tag `area=yes`.

Is necessary to improve this [line](https://github.com/osmlab/osmlint/blob/591f8adaa8800e8e13ab828bb4924509d8377620/validators/unclosedWays/map.js#L13) according above links  
cc @maning @planemad @geohacker

**Comment by maning** [comment]
@Rub21 there is a [minjur fix](https://github.com/mapbox/minjur/commit/e1dc6981a59be07e32f89b0b783c868eea07951a) that will go to the osm-qa tiles generation soon.  This fixes the issue of one object having polygon or linestring for closed ways.  So for this validator, lets focus only on linestrings.  

@geohacker said the fix will be deployed soon in OSM-QA tiles

**Comment by Rub21** [comment]
@maning  sure!, yeah minjur was fixed, couple of hour  ago  the new mbtiles which contain polygon was released,for planet and per country 

>  lets focus only on linestrings.

yes,  we have to check out if the Linestring contain  a polygon tag, (aeroway, landuse, leisure, natural, etc).

**Comment by Rub21** [comment]
@maning  result here : http://geojson.io/#id=gist:anonymous/038169f69f4935cae89d&map=6/-16.415/-45.066

https://github.com/osmlab/osmlint/commit/e6bd4d89cd796b33767176d5894bb4a74cf4a9f7

## Next Acction

- [ ] Merge the [unclosedways](https://github.com/osmlab/osmlint/tree/unclosedways) branch to master branch

cc @geohacker

**Comment by Rub21** [comment]
done!

**Comment by maning** [comment]
Tested and confirmed this works as expected! :rocket:
