### ISSUE TITLE
Missing OSM tags in missinghighwayus

### ISSUE THREAD

**Issue by maning** [osmlab/osmlint#30]
From this result: https://gist.github.com/anonymous/9826ffad68ac64d272f4
we should include: `_version, _changeset, _user and highway` properties.

@Rub21

**Comment by Rub21** [comment]
@maning  done here! https://github.com/osmlab/osmlint/commit/09fef7af06c589c3192b21da40845659add6c82b

**Comment by maning** [comment]
From your sample data, user, version and changeset are missing.
