### ISSUE TITLE
[Validator] Crossing highways

### ISSUE THREAD

**Issue by geohacker** [osmlab/osmlint#31]
@Rub21 - questions:

0. Do you not want to filter for highways? https://github.com/osmlab/osmlint/blob/crossinghighways/validators/crossingHighways/map.js#L8
1. What does this bit of code do? https://github.com/osmlab/osmlint/blob/crossinghighways/validators/crossingHighways/map.js#L20-L25 It seems to me that you are finding the intersecting point, but you already have the [intersecting point](https://github.com/osmlab/osmlint/blob/crossinghighways/validators/crossingHighways/map.js#L17)? 
2. Does turf.intersect work on LineStrings? https://github.com/osmlab/osmlint/blob/crossinghighways/validators/crossingHighways/map.js#L17
3. I think we don't need to find all the intersecting points? https://github.com/osmlab/osmlint/blob/crossinghighways/validators/crossingHighways/map.js#L26-L34 

I'd probably try and simplify this first, @Rub21. 
cc @maning @batpad

**Comment by Rub21** [comment]
@geohacker 
> Do you not want to filter for highways? https://github.com/osmlab/osmlint/blob/crossinghighways/validators/crossingHighways/map.js#L8

yes, I considered  detect all the highways,  maybe we can do a filter for main highways.[e.g](https://github.com/mapbox/tile-reduce-processors/blob/mbtiles/processors/intersect/intersect.js#L10-L19),

> What does this bit of code do? https://github.com/osmlab/osmlint/blob/crossinghighways/validators/crossingHighways/map.js#L20-L25 It seems to me that you are finding the intersecting point, but you already have the intersecting point?

first we do the intersection, if it found an intersection point, this should be verify if this point is not a point to [concatenate two highways. ](https://www.openstreetmap.org/node/1417703705/history).

> Does turf.intersect work on LineStrings? https://github.com/osmlab/osmlint/blob/crossinghighways/validators/crossingHighways/map.js#L17

turf.intersect is working for LineStrings as well.

> I think we don't need to find all the intersecting points? https://github.com/osmlab/osmlint/blob/crossinghighways/validators/crossingHighways/map.js#L26-L34

I don't get  this question, so I think our target is find all the intersection between highways. 


I will figure out more how to improve this, i was  focusing more in crossing buildings.

**Comment by Rub21** [comment]
Crossing highways is working fine: 
we need to be agree what should be the output?
right away the output are: 

- LineString : For highways.
- Point : intersection in a point among two highways. 
- MultiPoint : intersection in more than two points  among two highways. 

Result for [Peru](https://gist.github.com/anonymous/aceca3a5fb34d65c31d8) take 8 min on my laptop.  I am using `rbush` to do it much faster as possible.

## Next Action

- [ ] Merge to Crossinghighways to master  https://github.com/osmlab/osmlint/pull/42

cc./ @geohacker @batpad @maning

**Comment by maning** [comment]
Detected errors good.

> LineString : For highways.
> Point : intersection in a point among two highways. 

Lets keep ^^ in the output geojson.

**Comment by Rub21** [comment]
Merge  in master , close here!
