### ISSUE TITLE
Question about Unclosed Ways validator

### ISSUE THREAD

**Issue by batpad** [osmlab/osmlint#33]
@Rub21 I see that you removed these lines:

https://github.com/osmlab/osmlint/commit/e6bd4d89cd796b33767176d5894bb4a74cf4a9f7#diff-5574e52da6d61bfcdad50304176ac7dfL18

^ Where it actually checks if the first coordinate is the same as the last coordinate or not. I am not sure how the current code can work without that line. Was it removed by mistake?

**Comment by Rub21** [comment]
@batpad  sorry, it was a mistake, I've simplified the code for avoiding closed ways, almost all false positive are closed ways in multipolygons, 
https://github.com/osmlab/osmlint/commit/ed762db2f5e5ca21696fdef87107ea4f2fb5c0c6
I think for now is okay, until get a good support for multipolygon in osm-qa-tiles.

cc. @geohacker

**Comment by Rub21** [comment]
@batpad , according the last  improvement in [minjur](https://github.com/mapbox/minjur/commit/e1dc6981a59be07e32f89b0b783c868eea07951a), it is using a list of tags that signify that a way is a polygon. so, if we found a LineString which uses this [list of tag](https://github.com/osmlab/osmlint/blob/master/validators/unclosedWays/value_area.js) , it should be consider unclosed way but I am doing other evaluations as well. 
The unclosedway result is https://github.com/osmlab/osmlint/issues/28#issuecomment-169366834
