### ISSUE TITLE
Untagged Ways validator: checking geometry.value, bug?

### ISSUE THREAD

**Issue by batpad** [osmlab/osmlint#34]
This line: https://github.com/osmlab/osmlint/blob/master/validators/untaggedWays/map.js#L36

Should that not be `if (value.geometry.type === 'Polygon')` and not `if (value.geometry.value === 'Polygon')` ?

@Rub21 ^

**Comment by Rub21** [comment]
@batpad  sorry, it was a mistake, I've simplified the code for avoiding closed ways, almost all false positive are closed ways in multipolygons, 
https://github.com/osmlab/osmlint/commit/ed762db2f5e5ca21696fdef87107ea4f2fb5c0c6
I think for now is okay, until get a good support for multipolygon in osm-qa-tiles.

cc. @geohacker
