### ISSUE TITLE
Map to visualize osmlint output

### ISSUE THREAD

**Issue by planemad** [osmlab/osmlint#35]
Made a quick style with the osmlint test output for PH

<img width="734" alt="screenshot 2016-01-13 12 26 38" src="https://cloud.githubusercontent.com/assets/126868/12287443/be36ed5c-b9f2-11e5-8ecd-88d44fd3c9d6.png">

[View Map](https://api.mapbox.com/styles/v1/planemad/cijcefp3q00elbskq4cgvcivf.html?title=true&access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#17.2/11.11786/125.00461) | [style.json](https://github.com/mapbox/mapping/blob/master/Studio/styles/osmlint-dark.json)

In the long run, having a simple frontend like [osm-sidewalker](https://www.mapbox.com/osm-sidewalker/#4/39.06/-98.90) that allows anyone to edit the object in iD/JOSM directly from the map will make this a readily useful tool.

@Rub21 @maning as we expand osmlint coverage, we can test the output on this map to see if we are getting the expected result and figure out how to visualize this on the map for better visual debugging.

cc @geohacker @mikelmaron @lxbarth @batpad

**Comment by planemad** [comment]
@geohacker @Rub21 is there a common place where we are storing the latest osmlint output? How can I continuously update this map?

**Comment by planemad** [comment]
<img width="548" alt="screenshot 2016-01-13 17 53 56" src="https://cloud.githubusercontent.com/assets/126868/12294239/ad115298-ba1e-11e5-904b-1ed273a01294.png">

Quick 1 hour hack for the frontend: http://planemad.github.io/osmlint-frontend/

Uses boilerplate code from the flood-map

**Comment by geohacker** [comment]
@planemad I think this should be outside of osmlint. osmlint is a command line utility and node module and will be developed independent of how someone would choose to visualise.

**Comment by planemad** [comment]
@geohackerif yes, for now it is just a generic tool to open objects in a GL map in JOSM. The experience of inspecting the osmlint data using this for me was more quicker than using the [geojson dashboard](http://maning.github.io/geojson-dashboard/#split)
