### ISSUE TITLE
[Validator] Crossing waterways and highways

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#44]
cc . @geohacker @batpad @maning

**Comment by Rub21** [comment]
- Result. https://gist.github.com/anonymous/c262d7cfcb9297436143
- Branch : https://github.com/osmlab/osmlint/tree/crossingwaterwayshighways

I think the PR should be created after merge the branch from [crossinghighways](https://github.com/osmlab/osmlint/pull/42) and [crossingbuildings](https://github.com/osmlab/osmlint/pull/41). 

What do you think @geohacker ?

@maning: can you take a look on the result. ?

**Comment by maning** [comment]
I'm seeing false positive, let's add tag filtering.
* highway - `bridge=*`, `tunnel=*`
* waterways - `waterway=dam, weir, waterfall`
* others - `ford=yes` on node where waterway and road intersects

@Rub21 @planemad

**Comment by Rub21** [comment]
@maning 
> highway - bridge=*, tunnel=*
> waterways - waterway=dam, weir, waterfall
> others - ford=yes on node where waterway and road intersects

is nice discuss about those stuff, it help me to take care on all kind of objects, I did the filter  the new result are: https://gist.github.com/anonymous/e57bc52b490c4cad8456.

Also we focus the analize for the main roads, which are crossing with waterways.: https://github.com/osmlab/osmlint/blob/crossingwaterwayshighways/validators/crossingWaterwaysHighways/map.js#L12-L19

### Next action 
- [ ] merge the crossingwaterwayshighways branch to master

cc. @geohacker

**Comment by maning** [comment]
@Rub21 
> is: https://gist.github.com/anonymous/e57bc52b490c4cad8456.

Detected errors are all OK.  Either it doesn't have a bridge tag or the node intersection doesn't have ford tag.

> Also we focus the analize for the main roads, which are crossing with waterways.:

I found one on a service road: https://www.openstreetmap.org/way/385190123/history

Overall, this linter works as expected. Can we have the output similar to the crossinghighways?
A point for the location of error and separate features for highway and waterways.  So that we can still include other osm metadata.

**Comment by Rub21** [comment]
@maning :
> A point for the location of error and separate features for highway and waterways. So that we can still include other osm metadata.

Sound fine: 

New [result](https://gist.github.com/anonymous/6eeaa3eaaabf26cf0fd1) include point and Linestring( highway and waterways)

![image](https://cloud.githubusercontent.com/assets/1152236/12590554/9e8eb8f6-c431-11e5-9f74-54751750a85a.png)

**Comment by Rub21** [comment]
done!  This validator was merge to master.
