### ISSUE TITLE
[Validator] Disconnected Highways

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#47]
cc. @geohacker @batpad @maning

**Comment by Rub21** [comment]
Done here!
##### Results:
on my laptop:
- [Peru](https://gist.github.com/anonymous/e6a70014e5e7f7283d38) 42 seg.
- [Brazil](https://gist.github.com/anonymous/1b5a8d58b2c66d3e9c79) 4 min

[Branch](https://github.com/osmlab/osmlint/tree/disconnectedhighways).

@maning can you check out the results.

**Comment by maning** [comment]
Mostly good, but some false-positives, sample below:
* https://www.openstreetmap.org/way/303545817/history
* https://www.openstreetmap.org/way/385191390/history
* https://www.openstreetmap.org/way/227361420/history
* https://www.openstreetmap.org/way/220533811/history
* https://www.openstreetmap.org/way/39100079/history

My guess is that you removed the [connecting ways](https://github.com/osmlab/osmlint/blob/disconnectedhighways/validators/disconnectedHighways/map.js#L16) before evaluating the disconnection.

Also, can we have a better name? Other validation tools call it *unconnected highways* or *island roads*.

**Comment by Rub21** [comment]
> Also, can we have a better name? Other validation tools call it unconnected highways or island roads.

 **unconnected highways**, sound better.

**Comment by Rub21** [comment]
The name  for this validator is `islands highways`
