### ISSUE TITLE
Full tests

### ISSUE THREAD

**Issue by lxbarth** [osmlab/osmlint#5]
- [ ] Add a TIGER test fixture to test `missingHighwaysUS`
- [ ] Test output of each processor

**Comment by Rub21** [comment]
@lxbarth @geohacker 
> Add a TIGER test fixture to test missingHighwaysUS

some progress here https://github.com/osmlab/osmlint/commit/b3eed2d3d60fd0ff4681344fb840133b68df4d3c 
I added two mbtiles files from Levy County, Florida to do the test
https://github.com/osmlab/osmlint/tree/missingnameus/test/fixtures
Testing result is ok.

**Comment by Rub21** [comment]
@geohacker @lxbarth 

I've done the test of stdout: 

- The output is a valid GeoJSON
- The FeatureCollection.
- The _osmlint property
- The type of geometry , LineString, Point or Polygon , according the validator

what else should we test?  thoughts?
