### ISSUE TITLE
Add rub21 in npm collaborators 

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#56]
@geohacker :

I've built many validators on this repo, not sure why is not appear my user name. Pls, Could you add my user name ([rub21](https://www.npmjs.com/~rub21)) on npm collaborators for [osmlint](https://www.npmjs.com/package/osmlint)? 
Thanks,

cc. @lxbarth

**Comment by lxbarth** [comment]
@Rub21 - you're already on there? What permission are you missing?

**Comment by geohacker** [comment]
Done @Rub21!
