### ISSUE TITLE
Split unconnectedHighways

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#61]
Split unconnected Highways in unconnected major and unconnected minor for recurring sweeps.
cc. @geohacker @maning

**Comment by geohacker** [comment]
@Rub21 Ah, this is a great idea. Do you think we should apply a property in the final geojson saying 'major' or 'minor'? I don't think we should create separate validators.

**Comment by Rub21** [comment]
>  we should apply a property in the final geojson saying 'major' or 'minor'? I don't think we should create separate validators.

 it sounds fine!

**Comment by Rub21** [comment]
done!
