### ISSUE TITLE
nodeendingnearhighway, highway=path and highway=steps

### ISSUE THREAD

**Issue by ianlopez1115** [osmlab/osmlint#68]
An instance of osmlint encountered false positives while checking for errors in the data.

![errorerror1a](https://cloud.githubusercontent.com/assets/1140532/13448914/9190dad8-dfdb-11e5-8ad0-b3e961743077.png)

The image above shows a nodeendingnearhighway error (two path that were seemingly disconnected to each other).

![errorerror2a](https://cloud.githubusercontent.com/assets/1140532/13448913/91677792-dfdb-11e5-8103-6412616322ba.png)

But when I opened JOSM, the paths were connected by a bridge (see image above)

![errorerror3a](https://cloud.githubusercontent.com/assets/1140532/13448963/dd320890-dfdb-11e5-8066-f06dca1c9a86.png)

A similar case occurred when footways were seeming disconnected from other footways. In one case, one footway was disconnected from a nearby road.

![errorerror4a](https://cloud.githubusercontent.com/assets/1140532/13449013/41f26856-dfdc-11e5-8ab3-2db82a3fd26c.png)

However, the footways (on the left side of the previous image) were connected by some steps. Same case with the steps which connected the footway to a nearby road.

**Comment by maning** [comment]
Thanks @ianlopez1115.

@Rub21, please add [highway=steps](https://github.com/osmlab/osmlint/blob/master/validators/nodeEndingNearHighway/map.js#L37).

**Comment by Rub21** [comment]
@ianlopez1115 , thanks you for reporting this problem, could you update you osmlint , i updated this error few days ago.
