### ISSUE TITLE
Falsos positvos en TOFIX - Unconnected Major

### ISSUE THREAD

**Issue by luisalanya** [osmlab/osmlint#71]
La deteccion del error no es correcta, ubica nodos que pertencen a un puente, cerca de una via que no tiene: layer = 2 @Rub21 
![error3](https://cloud.githubusercontent.com/assets/6518771/13502993/40ecaeac-e13b-11e5-818b-d5cdd9bf0acf.png)

**Comment by karitotp** [comment]
I found this case too; where the two bridge have diferent layer tag and the tunnel have layer = -1.

https://www.openstreetmap.org/changeset/14804127
![tofix](https://cloud.githubusercontent.com/assets/11504548/13503245/6633fd22-e13c-11e5-87fc-caa2889024c6.png)

**Comment by Rub21** [comment]
fixed!
