### ISSUE TITLE
Accidental merging of nodes 

### ISSUE THREAD

**Issue by jinalfoflia** [osmlab/osmlint#73]
Following up on some recent OSM vandalism of all the [roads being merged at a point](https://osmcha-django-staging.tilestream.net/37601982/):

![screen shot 2016-03-04 at 2 59 09 pm](https://cloud.githubusercontent.com/assets/4470913/13525978/e0a0378a-e22a-11e5-84e6-e7a58cd9201a.png)

Is there a possibility to detect instances like these where multiple nodes have been accidentally moved or merged?

/cc @Rub21 @geohacker @mikelmaron @lxbarth @maning

**Comment by Rub21** [comment]
@jinalfoflia - This kind of errors  should detected by crossingHighways validator.   the point out should  run it daily.

**Comment by Rub21** [comment]
these errors  are detecting by impossible angle  or crossingHighways validator.
