### ISSUE TITLE
Exclude highways with bridge and tunnel tags in the crossinghighway linter

### ISSUE THREAD

**Issue by maning** [osmlab/osmlint#77]
I'm seeing false positives for crossing highways where the other highway has a `bridge` or `tunnel` tag.
Let's exclude them in the linter.

@Rub21 @geohacker

**Comment by Rub21** [comment]
@maning On these  `bridge` and  `tunnel`  missing tag `layer=*`.

**Comment by maning** [comment]
The linter works as expected, the error I found was a tagging issue (`level` instead of `layers`).
Closing, sorry for the noise.
