### ISSUE TITLE
[Validator]Impossible angle

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#83]
This validator should be implemented, because there are many cases that are of this type.
![image](https://cloud.githubusercontent.com/assets/1152236/14146056/e61b0678-f65b-11e5-8372-c2de189c2354.png)

![image](https://cloud.githubusercontent.com/assets/1152236/14145854/0470bdda-f65b-11e5-9c94-96b648a1ea45.png)

See also : https://github.com/osmlab/osmlint/issues/73

cc. @maning @planemad

**Comment by aaronlidman** [comment]
This was previously called "kinks" by keepright.

**Comment by Rub21** [comment]
@aaronlidman  do you see is necessary add this kind of algorithm  in osmlint, or can we continue using keepright?

**Comment by aaronlidman** [comment]
Yeah let's do it in osmlint.

**Comment by Rub21** [comment]
This validator was added in osmlint https://github.com/osmlab/osmlint/tree/master/validators/impossibleAngle
